{% set name = "openpmd-api" %}
{% set version = "0.6.3a" %}
{% set sha256 = "8dca9303f2597937217de4446e1fe9aaf71c7a019393246be40603813956dcc8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: 0.6.3-alpha.tar.gz
  url: https://github.com/openPMD/openPMD-api/archive/0.6.3-alpha.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-Add-CMAKE_FIND_ROOT_PATH-to-ADIOS_LIBRARY_DIRS.patch

build:
  number: 1001
  # Python 2.7 stack is build with too ancient vc9 (VS2008)
  skip: True  # [win and py27]

requirements:
  build:
    - {{ compiler('cxx') }}
    - make  # [unix]
    - cmake >=3.10
  host:
    - python
    - pybind11 >=2.2.3
    - adios >=1.13.1  # [unix]
    - hdf5  >=1.8.13
    - blosc
    - bzip2
    - zlib
  run:
    - python
    - adios >=1.13.1  # [unix]
    - hdf5  >=1.8.13
    - numpy >=1.15.0
    - blosc
    - bzip2
    - zlib

test:
  requires:
    - numpy >=1.15.0
  imports:
    - openPMD
  commands:
    - python -c "import openPMD; print(openPMD.__version__);"
    - python -c "import openPMD; print(openPMD.variants)"
    - test -f ${PREFIX}/lib/cmake/openPMD/openPMDConfig.cmake             # [unix]
    - if exist %PREFIX%\cmake\openPMDConfig.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://www.openPMD.org
  license: LGPL 3
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: 'C++ & Python API for writing & reading (H5, BP, ...), serial & MPI parallel openPMD files.'

  description: |
    This library provides a common high-level API for openPMD writing and
    reading. It provides a common interface to I/O libraries and file formats
    such as HDF5 and ADIOS.
    This conda-forge package only provides serial I/O, please build from source
    for MPI parallel I/O on HPC systems. Window support is limited to HDF5 and
    Python 3.
  doc_url: https://openpmd-api.readthedocs.io
  dev_url: https://github.com/openPMD/openPMD-api

extra:
  recipe-maintainers:
    - ax3l
    - C0nsultant
